; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.36"

; Modules
projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.4"

projects[bean][subdir] = "contrib"
projects[bean][version] = "1.9"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.16"

projects[color_field][subdir] = "contrib"
projects[color_field][version] = "1.7"

projects[context][subdir] = "contrib"
projects[context][version] = "3.6"

projects[content_menu][subdir] = "contrib"
projects[content_menu][version] = "1.0"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.7"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[date_ical][subdir] = "contrib"
projects[date_ical][version] = "3.3"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[entity_translation][subdir] = "contrib"
projects[entity_translation][version] = "1.0-beta4"

projects[features][subdir] = "contrib"
projects[features][version] = "2.5"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.6"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.12"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.5"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "2.0"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[linkchecker][subdir] = "contrib"
projects[linkchecker][version] = "1.2"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.4"

projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.7"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[redis][subdir] = "contrib"
projects[redis][version] = "2.12"

projects[robotstxt][subdir] = "contrib"
projects[robotstxt][version] = "1.3"

projects[scald][subdir] = "contrib"
projects[scald][version] = "1.3"

projects[scheduler][subdir] = "contrib"
projects[scheduler][version] = "1.3"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.10"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[webform][subdir] = "contrib"
projects[webform][version] = "4.7"

projects[workbench_email][subdir] = "contrib"
projects[workbench_email][version] = "3.3"

projects[workbench_moderation][subdir] = "contrib"
projects[workbench_moderation][version] = "1.4"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.2"

; Themes
projects[adminimal_theme][version] = "1.21"
projects[adminimal_theme][subdir] = "contrib"

projects[navbar][version] = "1.6"
projects[navbar][subdir] = "contrib"

; Libraries
libraries[backbone][download][type] = "get"
libraries[backbone][download][url]  = "http://backbonejs.org/backbone-min.js"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type]           = "library"

libraries[underscore][download][type] = "get"
libraries[underscore][download][url]  = "https://github.com/jashkenas/underscore/archive/1.5.2.zip"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type]           = "library"

libraries[modernizr][download][type] = "get"
libraries[modernizr][download][url]  = "https://github.com/Modernizr/Modernizr/archive/v2.8.3.zip"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type]           = "library"

libraries[spectrum][download][type] = "get"
libraries[spectrum][download][url]  = "https://github.com/bgrins/spectrum/archive/1.6.2.zip"
libraries[spectrum][directory_name] = "bgrins-spectrum"
libraries[spectrum][type]           = "library"
